server:
  port: 0

spring:
  application:
    name: application-service
  cloud:
    discovery:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        max_fetch_depth: 3
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: ${APP_DB_URL:jdbc:postgresql://localhost:5436/appdb}
    username: ${APP_DB_USER:postgres}
    password: ${APP_DB_PASS:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:9092,kafka2:9092,kafka3:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 10
      enable-idempotence: true
      delivery-timeout-ms: 120000
      request-timeout-ms: 30000
      max-block-ms: 60000
    consumer:
      group-id: application-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        session.timeout.ms: 45000
        max.poll.interval.ms: 300000
        enable.auto.commit: false
    listener:
      ack-mode: manual_immediate
    topics:
      user-deleted: user.deleted
      product-deleted: product.deleted
      tag-create-request: tag.create.request
      tag-attach-request: tag.attach.request
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      user-service:
        baseConfig: default
      product-service:
        baseConfig: default
      tag-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      user-service:
        baseConfig: default
      product-service:
        baseConfig: default
      tag-service:
        baseConfig: default

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

logging:
  level:
    com.example: DEBUG
    org.springframework.cloud: INFO

jwt:
  secret: "3c04092ee33e6d63aeded3617cd159e3742ecb417c364106cc75efa2c18dd2eb5bf70af5"
  expiration-ms: 3600000